
// This is an example event type generated by `graph-cli`
// from an Ethereum smart contract ABI
import { Transfer } from '../generated/MyERC721Contract/ERC721'

// This is an example of an entity type generated from a
// subgraph's GraphQL schema
import { Token } from '../generated/schema'

export function handleTransfer(event: Transfer): void {
    let tokenID = event.params.tokenId.toHex()
    let token = new Token(tokenID)
    token.currentOwner = event.params.to

    token.save()
}