version: "3"

networks:
  thegraph:
    name: graphNode-networks
  blockchain:
    name: bellecour_blockchain
    external: true

services:
  ipfs:
    container_name: ipfs-service
    image: ipfs/go-ipfs:v0.4.23
    restart: unless-stopped
    networks:
      - thegraph
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ipfs-volume:${DATA}/ipfs:/data/ipfs

  postgres:
    container_name: postgres-service
    image: postgres
    restart: unless-stopped
    networks:
      - thegraph
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - postgres-volume:${DATA}/postgres:/var/lib/postgresql/data

  graphnode:
    container_name: graphnode-service
    image: graphprotocol/graph-node
    restart: unless-stopped
    networks:
      - blockchain
      - thegraph
    depends_on:
      - ipfs
      - postgres
    ports:
      - 8000:8000 # http
      - 8001:8001 # ws
      - 8020:8020 # deploy
      - 8030:8030 # monitoring
      - 8040:8040 # prometeus
    environment:
      RUST_BACKTRACE: 1
      postgres_host: postgres
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "bellecour:http://archivenode-bellecour:8545"
      GRAPH_NODE_ID: "graphnode_id"

volumes:
  ipfs-volume:
  postgres-volume:
