[parity]
chain = "/home/openethereum/node-config/spec.json"
base_path = "parity_data"

[rpc]
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "parity", "traces"]
cors = ["all"]
hosts = ["all"]

[network]
reserved_peers="/home/openethereum/node-config/bootnodes.txt"
port = 30303
max_peers = 100

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "pubsub", "traces"]
hosts = ["all"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"

[misc]
log_file = "/home/openethereum/logs/openethereum.logs"
