version: "3.4"

networks:
  blockchain:
    name: bellecour_blockchain

services:
  bellecour_blockchain:
    container_name: archivenode-bellecour
    restart: unless-stopped
    image: "openethereum/openethereum:v3.3.5"
    command: --config="/home/openethereum/node-config/config.toml"
    expose:
      - "8545"
      - "8546"
    volumes:
      - $PWD/node-config/:/home/openethereum/node-config/
      - $PWD/logs/:/home/openethereum/logs/
      - $PWD/data/:/home/openethereum/parity_data/
    networks:
      - blockchain
